name: "Rename branch name"
on: pull_request_target

jobs:
  update-branch:
    name: Update dev branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo ${GITHUB_REF##*/}

      - name: Create Pull Request
        uses: peter-evans/create-or-update-project-card@v1
        with:
          branch: dependa-bot-branch
