name: "Rename branch name"
on: pull_request_target

jobs:
  update-branch:
    name: Update dev branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo ${GITHUB_REF##*/}
